// Luis Guillermo Niebla Rios

#include "sem.h"

struct TCB_t * RunQ;
struct TCB_t * waitQ;
struct TCB_t * touchedHistory;
#define DEBUG 0 
ucontext_t parent;
struct sem * empty;
struct sem * full;
struct sem * mutex;

void put(int value) {
    struct TCB_t * thisRecord = NewItem();
    thisRecord->identifier = RunQ->next->identifier;
    AddToEnd(touchedHistory, thisRecord);
    if (QueueLength(touchedHistory) > 6) {
        printf("We're violated the buffer rule size\n");
        exit(0);
    }
}

TCB_t * get() {
    TCB_t *head = DelQueue(touchedHistory);
    if (head == NULL) {
        printf("We've violated the buffer rule size\n");
        exit(0);
    }
    return head;
}

void producer_1() {
    int in = 1;
    while(1) {
        P(empty);
        put(in++);
        V(full);
        printf("This is %s producing item number %d\n", RunQ->next->identifier, in - 1);
        yield();
    }
}

void consumer_1() {
    while(1) {
        P(full);
        TCB_t * tmp =  get();
        V(empty);
        printf("This is %s consuming item generated by %s\n", RunQ->next->identifier, tmp->identifier);
        yield();
    }
}

int main() {
    waitQ = NewItem();
    touchedHistory = NewItem();
    touchedHistory->payload = 0;
    empty = (struct sem *) malloc(sizeof(struct sem));
    mutex = (struct sem *) malloc(sizeof(struct sem));
    full = (struct sem *) malloc(sizeof(struct sem));
    InitSem(empty, 6, "empty");
    empty->queue = NewItem();
    InitSem(full, 0, "full");
    full->queue = NewItem();
    RunQ = NewItem();
    RunQ->payload = 0;

    start_thread(consumer_1, 1, "Consumer 1");
    start_thread(consumer_1, 2, "Consumer 2");
    start_thread(consumer_1, 3, "Consumer 3");
    start_thread(producer_1, 1, "Producer 1");
    start_thread(producer_1, 2, "Producer 2");
    start_thread(producer_1, 3, "Producer 3");
    start_thread(producer_1, 4, "Producer 4");
    start_thread(producer_1, 5, "Producer 5");
    start_thread(producer_1, 6, "Producer 6");
    start_thread(producer_1, 7, "Producer 7");
    start_thread(consumer_1, 4, "Consumer 4");
    start_thread(consumer_1, 5, "Consumer 5");
    start_thread(consumer_1, 6, "Consumer 6");
    start_thread(consumer_1, 7, "Consumer 7");
    start_thread(consumer_1, 8, "Consumer 8");
    start_thread(consumer_1, 9, "Consumer 9");
    start_thread(consumer_1, 10, "Consumer 10");
    start_thread(producer_1, 8, "Producer 8");
    start_thread(producer_1, 9, "Producer 9");
    start_thread(producer_1, 10, "Producer 10");
    
    run();
}