#include "sem.h"

struct TCB_t * RunQ;
struct TCB_t * touchedHistory;

ucontext_t uctx_main;
ucontext_t parent;
struct sem * empty;
struct sem * full;
struct sem * mutex;
int buffer;
int buff[5];
int out;
int in;
int item;
int last_touched = 0;



void producer_1() {
    printf("\n\n=========Entering producer=============\n");
    yield();
    printf(">>>>>>>>>>>>>After yield on producer\n");
    yield();
    // while(1) {
    //     printf(">>>>>>>>>>Entering producer\n");
    //     P(empty);
    //     printf("Producer passed P(empty)\n");
    //     P(mutex);
    //     printf("Producer passed P(mutex)\n");
    //     buff[in] = 1;
    //     in++;
    //     V(mutex);
    //     V(full);
    //     printf("Producer adding item to record\n");
    //     struct TCB_t * thisRecord = NewItem();
    //     thisRecord->payload = 1;
    //     AddQueue(touchedHistory, thisRecord);
    //     PrintQueue(touchedHistory);
    //     printf("---Finished with producer---\n");
    //     yield();
    //     printf("-------Return FROM YIELD\n");
    // }
}

void consumer_1() {
    printf("\n\nBefore yield on consumer 1\n");
    
    yield();
    printf(">>>>>>>>>>>>>>After yield on consumer 1\n");
    // while(1) {
    //     printf("Entering Consumer\n");
    //     sleep(1);
    //     P(full);
    //     P(mutex);
    //     printf("Finished with blockers on consumer\n");
    //     item = buff[out];
    //     out = (out + 1) % 6;
    //     V(mutex);
    //     printf("Mutex is free\n");
    //     printf(empty);
    //     V(empty);
    //     printf("Empty is free\n");
    //     printf(empty->value);
    //     // buffer--;
    //     struct TCB_t * lastTouch = DelQueue(touchedHistory);
    //     if (lastTouch) {
    //         printf("This is consumer %d consuming item generated by producer %d\n", 1, lastTouch->payload);
    //     }else{
    //         printf("Consumer %d is waiting\n", 1);
    //     }
    //     printf("---Finished with Consumer---\n");
    //     yield();
    //     printf("===========RETURN FROM YIELD======\n");
    // }
}

int main() {
    printf("==============");
    out = 0;
    in = 0;
    touchedHistory = NewItem();
    touchedHistory->payload = 0;
    empty = (struct sem *) malloc(sizeof(struct sem));
    mutex = (struct sem *) malloc(sizeof(struct sem));
    full = (struct sem *) malloc(sizeof(struct sem));
    InitSem(empty, 1);
    InitSem(mutex, 1);
    InitSem(full, 6);
    RunQ = NewItem();
    RunQ->payload = 0;
    start_thread(consumer_1, 1);
    start_thread(producer_1, 2);
    getcontext(&parent);
    run();

}